### ISSUE TITLE
Doesn't compile with Cocoapods 0.36.0.rc.1

### ISSUE THREAD

**Issue by albertbori** [OliverLetterer/GHMarkdownParser#12]
When installing via Cocoapods:

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'
    use_frameworks!
    pod 'GHMarkdownParser'

I get the following compile time errors:

> /Users/me/dev/myapp-ios/Pods/GHMarkdownParser/discount/mkdio.h:6:14: Typedef redefinition with different types ('void' vs 'struct mmiot')
> /Users/me/dev/myapp-ios/Pods/GHMarkdownParser/discount/mkdio.h:12:8: Conflicting types for 'mkd_in'
> /Users/me/dev/myapp-ios/Pods/GHMarkdownParser/discount/mkdio.h:13:8: Conflicting types for 'mkd_string'
> /Users/me/dev/myapp-ios/Pods/GHMarkdownParser/discount/mkdio.h:17:8: Conflicting types for 'gfm_in'
> /Users/me/dev/myapp-ios/Pods/GHMarkdownParser/discount/mkdio.h:18:8: Conflicting types for 'gfm_string'
> /Users/me/dev/myapp-ios/Pods/GHMarkdownParser/discount/mkdio.h:20:6: Conflicting types for 'mkd_basename'
> /Users/me/dev/myapp-ios/Pods/GHMarkdownParser/discount/mkdio.h:28:5: Conflicting types for 'mkd_compile'
> /Users/me/dev/myapp-ios/Pods/GHMarkdownParser/discount/mkdio.h:29:6: Conflicting types for 'mkd_cleanup'
> /Users/me/dev/myapp-ios/Pods/GHMarkdownParser/discount/mkdio.h:48:5: Conflicting types for 'mkd_document'
> /Users/me/dev/myapp-ios/Pods/GHMarkdownParser/discount/mkdio.h:50:5: Conflicting types for 'mkd_css'
> /Users/me/dev/myapp-ios/Pods/GHMarkdownParser/discount/mkdio.h:55:5: Conflicting types for 'mkd_generatehtml'
> /Users/me/dev/myapp-ios/Pods/GHMarkdownParser/discount/mkdio.h:58:5: Conflicting types for 'mkd_generatecss'
> /Users/me/dev/myapp-ios/Pods/GHMarkdownParser/discount/mkdio.h:79:6: Conflicting types for 'mkd_ref_prefix'
> /Users/me/dev/myapp-ios/myapp/Views/MyClass.swift:11:8: Could not build Objective-C module 'GHMarkdownParser'

**Comment by blackfog** [comment]
I pulled it from CocoaPods and installed it directly as a sub-project according to the standard instructions, and in Xcode 6.3/6.4, I get the same errors and a failed build, as well.

**Comment by mritrifork** [comment]
This is a problem with the PodSpec and Swift. @OliverLetterer should add the tag.
